### ISSUE TITLE
Error: [PANIC] runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by PrymalInstynct** [Unpackerr/unpackerr#283]
I recently started running into an issue with Unpackerr running in Kubernetes and I cant seem to troubleshoot the root cause as nothing has changed that I am aware of.

Upon the container starting it will immediatly CrashBackOffLoop with the below Log messages

Did something change in the 0.11.1 release that is requiring a Sonarr config to be present during application start up? If so I would think this is a bug since not every user is going to utilize Unpackerr for the same tasks.

```
Defaulted container "unpackerr-uhd" out of: unpackerr-uhd, provide-timezone (init)
2023/04/10 19:53:53 Unpackerr v0.11.1 Starting! PID: 7, UID: 568, GID: 568, Now: 2023-04-10 19:53:53 -0600 MDT
2023/04/10 19:53:53 ==> GoLift Discord: https://golift.io/discord <==
2023/04/10 19:53:53 ==> Startup Settings <==
2023/04/10 19:53:53  => Sonarr Config: 0 servers
2023/04/10 19:53:53 [PANIC] runtime error: index out of range [0] with length 0
```

What is interesting is I have a second container running in the same namespace that is being used for Sonarr and non-HDR Radarr content and it is functioning just fine.

Below is the Helm Chart I am using to deploy this container into the cluster

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr-uhd
  namespace: media-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.11.1@sha256:8aa2e192f27fe2f6c22b4c73ec780507f2b26cfed26d4c906b1852f53a18d27d
    env:
      TZ: "${TIMEZONE}"
      UN_RADARR_0_URL: http://radarr-uhd.media-automation.svc.cluster.local
      UN_RADARR_0_PATHS_0: /complete/radarr-uhd
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      fsGroup: 0
    persistence:
      complete:
        enabled: true
        type: nfs
        server: "scorpion.${SECRET_PRIVATE_DOMAIN}"
        path: /volume1/data/media/downloads/complete
        mountPath: /complete
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1000Mi
```
