### ISSUE TITLE
Whisparr does not work with Docker Compose/Yaml

### ISSUE THREAD

**Issue by Simpuhl** [Unpackerr/unpackerr#395]
Tried these settings and it completely ignored them, I ended up having to add them to the conf file manually.

      # Whisparr Config
      - UN_WHISPARR_0_URL=http://192.168.0.XXX:6969
      - UN_WHISPARR_0_API_KEY=XXXXXXXXXXXXX
      - UN_WHISPARR_0_PATHS_0=/downloads/xxx-whisparr
      - UN_WHISPARR_0_PROTOCOLS=torrent
      - UN_WHISPARR_0_TIMEOUT=10s
      - UN_WHISPARR_0_DELETE_ORIG=false
      - UN_WHISPARR_0_DELETE_DELAY=5m

**Comment by davidnewhall** [comment]
Works for me.
```
$ UN_WHISPARR_0_API_KEY=1234 UN_WHISPARR_0_URL=https://foo1.com ./unpackerr
[INFO] 2024/02/09 17:07:43.858436 start.go:150: Unpackerr v0.12.0 Starting! PID: 78687, UID: 502, GID: 20, Now: 2024-02-09 17:07:44 -0800 PST
2024/02/09 17:07:43 [ERROR] Whisparr (https://foo1.com) provided application API Key is invalid, must be 32 characters, your key length: 4
```

**Comment by Simpuhl** [comment]
It also ignored 

# Folder Config

**Comment by davidnewhall** [comment]
Can you share your entire configuration so we can help you find the problem?

**Comment by Simpuhl** [comment]
name: unpackerr
services:
    unpackerr:
        container_name: unpackerr
        network_mode: bridge
        restart: unless-stopped
        stop_grace_period: 300s
        environment:
             - PUID=XXXX
             - PGID=XXX
             - UMASK=002
             - TZ=America/Los_Angeles
      # General config
             - UN_DEBUG=false
             - UN_LOG_FILE=
             - UN_LOG_FILES=10
             - UN_LOG_FILE_MB=10
             - UN_INTERVAL=2m
             - UN_START_DELAY=1m
             - UN_RETRY_DELAY=5m
             - UN_MAX_RETRIES=3
             - UN_PARALLEL=1
             - UN_FILE_MODE=0644
             - UN_DIR_MODE=0755
      # Sonarr Config
             - UN_SONARR_0_URL=http://192.168.0.178:8989
             - UN_SONARR_0_API_KEY=XXX
             - UN_SONARR_0_PATHS_0=/downloads/tv-sonarr
             - UN_SONARR_0_PROTOCOLS=torrent
             - UN_SONARR_0_TIMEOUT=10s
             - UN_SONARR_0_DELETE_ORIG=false
             - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
             - UN_RADARR_0_URL=http://192.168.0.178:7878
             - UN_RADARR_0_API_KEY=XXX
             - UN_RADARR_0_PATHS_0=/downloads/movies-radarr
             - UN_RADARR_0_PROTOCOLS=torrent
             - UN_RADARR_0_TIMEOUT=10s
             - UN_RADARR_0_DELETE_ORIG=false
             - UN_RADARR_0_DELETE_DELAY=5m
      # Lidarr Config
             - UN_LIDARR_0_URL=http://192.168.0.178:8686
             - UN_LIDARR_0_API_KEY=XXX
             - UN_LIDARR_0_PATHS_0=/downloads/music-lidarr
             - UN_LIDARR_0_PROTOCOLS=torrent
             - UN_LIDARR_0_TIMEOUT=10s
             - UN_LIDARR_0_DELETE_ORIG=false
             - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
             - UN_READARR_0_URL=http://192.168.0.178:8787
             - UN_READARR_0_API_KEY=XXX
             - UN_READARR_0_PATHS_0=/downloads/books-readarr
             - UN_READARR_0_PROTOCOLS=torrent
             - UN_READARR_0_TIMEOUT=10s
             - UN_READARR_0_DELETE_ORIG=false
             - UN_READARR_0_DELETE_DELAY=5m
      # Whisparr Config
             - UN_WHISPARR_0_URL=http://192.168.0.178:6969
             - UN_WHISPARR_0_API_KEY=XXX
             - UN_WHISPARR_0_PATHS_0=/downloads/xxx-whisparr
             - UN_WHISPARR_0_PROTOCOLS=torrent
             - UN_WHISPARR_0_TIMEOUT=10s
             - UN_WHISPARR_0_DELETE_ORIG=false
             - UN_WHISPARR_0_DELETE_DELAY=5m
      # Folder Config
             - UN_FOLDER_0_PATH=/downloads/Packs
             - UN_FOLDER_0_EXTRACT_PATH=
             - UN_FOLDER_0_DELETE_AFTER=10m
             - UN_FOLDER_0_DELETE_ORIGINAL=false
             - UN_FOLDER_0_DELETE_FILES=false
             - UN_FOLDER_0_MOVE_BACK=false
        volumes:
             - /volume1/docker/unpackerr:/config
             - /volume1/downloads:/downloads
        image: cr.hotio.dev/hotio/unpackerr:latest

**Comment by Simpuhl** [comment]
I notice it puts everything im the conf file, but it ignores Whisparr, and then looking at the logs it seems like folder config is working but it doesn't write that to the conf file at all. For some reason Unpackarr doesn't show up in Portainer for me but heres the log screenshot:

![image](https://github.com/Unpackerr/unpackerr/assets/262571/4f5421d7-a980-423f-829f-897d3ae0be60)

**Comment by davidnewhall** [comment]
**`cr.hotio.dev` stopped working a long time ago.** 

I copied your compose, replaced XXX with fake api keys, removed the volumes, and changes the image to `golift/unpackerr`. It did this.
<img width="1769" alt="Screen Shot 2024-02-10 at 12 30 11 AM" src="https://github.com/Unpackerr/unpackerr/assets/2402929/5fb6bbe6-f8df-4afe-9d47-560eaad2de22">

I cannot reproduce what you're reporting. 

```yaml
name: unpackerr
services:
    unpackerr:
        container_name: unpackerr
        network_mode: bridge
        restart: unless-stopped
        stop_grace_period: 300s
        environment:
             - PUID=XXXX
             - PGID=XXX
             - UMASK=002
             - TZ=America/Los_Angeles
      # General config
             - UN_DEBUG=false
             - UN_LOG_FILE=
             - UN_LOG_FILES=10
             - UN_LOG_FILE_MB=10
             - UN_INTERVAL=2m
             - UN_START_DELAY=1m
             - UN_RETRY_DELAY=5m
             - UN_MAX_RETRIES=3
             - UN_PARALLEL=1
             - UN_FILE_MODE=0644
             - UN_DIR_MODE=0755
      # Sonarr Config
             - UN_SONARR_0_URL=http://192.168.0.178:8989
             - UN_SONARR_0_API_KEY=12345678901234567891212345678901
             - UN_SONARR_0_PATHS_0=/downloads/tv-sonarr
             - UN_SONARR_0_PROTOCOLS=torrent
             - UN_SONARR_0_TIMEOUT=10s
             - UN_SONARR_0_DELETE_ORIG=false
             - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
             - UN_RADARR_0_URL=http://192.168.0.178:7878
             - UN_RADARR_0_API_KEY=12345678901234567891212345678901
             - UN_RADARR_0_PATHS_0=/downloads/movies-radarr
             - UN_RADARR_0_PROTOCOLS=torrent
             - UN_RADARR_0_TIMEOUT=10s
             - UN_RADARR_0_DELETE_ORIG=false
             - UN_RADARR_0_DELETE_DELAY=5m
      # Lidarr Config
             - UN_LIDARR_0_URL=http://192.168.0.178:8686
             - UN_LIDARR_0_API_KEY=12345678901234567891234567890121
             - UN_LIDARR_0_PATHS_0=/downloads/music-lidarr
             - UN_LIDARR_0_PROTOCOLS=torrent
             - UN_LIDARR_0_TIMEOUT=10s
             - UN_LIDARR_0_DELETE_ORIG=false
             - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
             - UN_READARR_0_URL=http://192.168.0.178:8787
             - UN_READARR_0_API_KEY=12345678901234567891212345678901
             - UN_READARR_0_PATHS_0=/downloads/books-readarr
             - UN_READARR_0_PROTOCOLS=torrent
             - UN_READARR_0_TIMEOUT=10s
             - UN_READARR_0_DELETE_ORIG=false
             - UN_READARR_0_DELETE_DELAY=5m
      # Whisparr Config
             - UN_WHISPARR_0_URL=http://192.168.0.178:6969
             - UN_WHISPARR_0_API_KEY=12345678901234567891212345678901
             - UN_WHISPARR_0_PATHS_0=/downloads/xxx-whisparr
             - UN_WHISPARR_0_PROTOCOLS=torrent
             - UN_WHISPARR_0_TIMEOUT=10s
             - UN_WHISPARR_0_DELETE_ORIG=false
             - UN_WHISPARR_0_DELETE_DELAY=5m
      # Folder Config
             - UN_FOLDER_0_PATH=/downloads/Packs
             - UN_FOLDER_0_EXTRACT_PATH=
             - UN_FOLDER_0_DELETE_AFTER=10m
             - UN_FOLDER_0_DELETE_ORIGINAL=false
             - UN_FOLDER_0_DELETE_FILES=false
             - UN_FOLDER_0_MOVE_BACK=false
        image: golift/unpackerr
```
