### ISSUE TITLE
Password File

### ISSUE THREAD

**Issue by david1111967** [Unpackerr/unpackerr#407]
I'm trying to set up a password file but I'm not able to get it done

My docker compose has the following

```
unpackerr:
    image: golift/unpackerr
    ports:
      - 5656:5656
    environment:
      - TZ=Europe/Madrid
      - PUID=1053
      - PGID=65538
      - UMASK=002
      - UN_PASSWORD_0="filepath:/config/passwords.txt"
    volumes:
      - ./config/unpackerr:/config
      - ./data/torrents:/data/torrents
    networks:
      - servarr`'
```
And my password file contains multiple passwords as follows

```
123412312312
1234123123
```

Any information would be helpful
