### ISSUE TITLE
Docker Rootless support?

### ISSUE THREAD

**Issue by kaitallaoua** [Unpackerr/unpackerr#496]
Trying to isolate if a permission issue (dont think so) or if this program has been tested or has issues with docker-rootless. 

```
services:
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /active_torrents:/downloads
    restart: always
    user: 1000:1000
    environment:
      - TZ=A/ValidTZ
      - UN_LOG_FILE=/downloads/unpackerr.log
      - UN_SONARR_0_URL=http://redact:8989
      - UN_SONARR_0_API_KEY=redact
      - UN_RADARR_0_URL=http://redact:7878
      - UN_RADARR_0_API_KEY=redact
      - UN_FOLDER_0_PATH=/downloads
```

First tried on an alpine vm running docker-rl. Had errors like: `Logger Error: error with new logfile: open /downloads/unpackerr.log: permission denied` and if I removed the log file, it could not find the files, even though I was 100% sure mounts were set right and perms seemed good. Tried on a ubuntu vm with rooted docker, exact same compose file, exact same nfs mounted with same path, and it worked. Ownership of the files is the same user/group id accross all machines. Downloads folder matches volume mount of sonarr and radarr. Even the permissions themselves I tried with `777` but still no luck. By process of elimination, docker-rl seems the issue. Has it been tested on it, or am I doing something wrong?
