### ISSUE TITLE
Strange Permission Issue I Cannot Pin Down

### ISSUE THREAD

**Issue by epoch-philosophy** [Unpackerr/unpackerr#542]
Hey, all. Hopefully this is something simple, but I've been racking my head around this, I've read the documentation probably 3 times over, and the logs aren't making too much sense to me.

I am seeing this log throughout my Unpackerr container:
```
Logger Error: making directories for logfiles: mkdir /downloads: permission denied
Logger Error: making directories for logfiles: mkdir /downloads: permission denied
Logger Error: making directories for logfiles: mkdir /downloads: permission denied
```

My compose file is as follows:
```
  unpackerr:
    image: golift/unpackerr:latest
    networks:
      - proxy
    container_name: unpackerr
    volumes:
      - /mnt/user/data:/data
    restart: always
    user: 99:100
    environment:
      - TZ=${TZ}
      - UN_LOG_FILE=/downloads/unpackerr.log
      - UN_SONARR_0_URL=${SONARR_API_URL}
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=${RADARR_API_URL}
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_DEBUG=true
```

I am hosting this on an Unraid server. I am just using docker compose rather than it's UI. So, my permissions of 99:100 should be correct, the file permissions are accurately pinned under the Unraid user "nobody". I'm unaware what "/downloads" in the container is, and why there may be permission issues.

Any help would be appreciated!
